services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces
    command: sleep infinity
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname=nyaweria_dev
      interval: 5s
      timeout: 2s
      retries: 3
    environment:
      POSTGRES_USER: nyaweria_rw
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: nyaweria_dev

volumes:
  db-data:
