ALTER TABLE donations
  ADD created_at TIMESTAMP CONSTRAINT default_created_at DEFAULT CURRENT_TIMESTAMP,
  ADD updated_at TIMESTAMP CONSTRAINT default_updated_at DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
  ADD created_at TIMESTAMP CONSTRAINT default_created_at DEFAULT CURRENT_TIMESTAMP,
  ADD updated_at TIMESTAMP CONSTRAINT default_updated_at DEFAULT CURRENT_TIMESTAMP;
